"""add_tag_in_table

Revision ID: d04b420a1170
Revises: ebcd5e3f512e
Create Date: 2025-01-17 15:15:00.690641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04b420a1170'
down_revision: Union[str, None] = 'ebcd5e3f512e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tarefas', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tarefas', 'tag')
    # ### end Alembic commands ###
